### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by fellz** [mattkrick/meatier#47]
Hi interesting project but failed to install. Here is the error
failed at this step
```rimraf build && concurrent "npm run build:client" "npm run build:server```

```
 ERROR in Entry module not found: Error: Cannot resolve module 'universal/modules/kanban/containers/Kanban/KanbanContainer.js' in /home/bob/code/meatier/src
[0] 
[0] ERROR in ./universal/redux/makeReducer.js
[0] Module not found: Error: Cannot resolve 'file' or 'directory' ../modules/auth/ducks/auth in /home/bob/code/meatier/src/universal/redux
[0]  @ ./universal/redux/makeReducer.js 17:12-49
[0] 
[0] ERROR in ./universal/routes/kanban.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/kanban/containers/Kanban/KanbanContainer' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/kanban.js 68:32-107
[0] 
[0] ERROR in ./universal/routes/kanban.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/kanban/ducks/lanes' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/kanban.js 68:174-227
[0] 
[0] ERROR in ./universal/routes/kanban.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/kanban/ducks/notes' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/kanban.js 68:240-293
[0] 
[0] ERROR in ./universal/routes/graphql.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/admin/components/Graphql/Graphql' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/graphql.js 21:21-88
[0] 
[0] ERROR in ./universal/routes/login.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/auth/containers/auth/AuthContainer' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/login.js 26:23-92
[0] 
[0] ERROR in ./universal/routes/signup.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/auth/containers/auth/AuthContainer' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/signup.js 25:23-92
[0] 
[0] ERROR in ./universal/routes/login.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/auth/components/LostPassword/LostPassword' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/login.js 58:27-103
[0] 
[0] ERROR in ./universal/routes/login.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/auth/components/ResetEmailSent/ResetEmailSent' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/login.js 89:27-107
[0] 
[0] ERROR in ./universal/routes/login.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/auth/components/ResetPassword/ResetPassword' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/login.js 120:27-105
[0] 
[0] ERROR in ./universal/routes/login.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/auth/components/ResetPasswordSuccess/ResetPasswordSuccess' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/login.js 151:27-119
[0] 
[0] ERROR in ./universal/routes/logout.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/auth/components/Logout/Logout' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/logout.js 21:21-85
[0] 
[0] ERROR in ./universal/routes/verifyEmail.js
[0] Module not found: Error: Cannot resolve module 'universal/modules/auth/containers/VerifyEmail/VerifyEmailContainer' in /home/bob/code/meatier/src/universal/routes
[0]  @ ./universal/routes/verifyEmail.js 21:21-104
[0] 
[0] ERROR in ./universal/decorators/loginWithToken/loginWithToken.js
[0] Module not found: Error: Cannot resolve 'file' or 'directory' ../../modules/auth/ducks/auth in /home/bob/code/meatier/src/universal/decorators/loginWithToken
[0]  @ ./universal/decorators/loginWithToken/loginWithToken.js 13:12-52

```
node v5.4.0
npm  v3.3.12

**Comment by mattkrick** [comment]
can you verify that you've got webpack 2 installed globally? it may be caused because it doesn't know what to do with system.import.

**Comment by fellz** [comment]
ok installed webpack globally then run ```npm run quickstart ```
something wrong with socketscluster
``` Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to localhost:28015\nFull error:\n{\"code\":\"ECONNREFUSED\",\"errno\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"127.0.0.1\",\"port\":28015}.","isOperational":true}
```
and this error
```
 ERROR in ./universal/routes/login.js
[1] Module not found: Error: Cannot resolve module 'universal/modules/auth/containers/auth/AuthContainer' in /home/goracio/code/js/meatier/src/universal/routes
[1]  @ ./universal/routes/login.js 26:23-92
[1] 
[1] ERROR in ./universal/routes/signup.js
[1] Module not found: Error: Cannot resolve module 'universal/modules/auth/containers/auth/AuthContainer' in /home/goracio/code/js/meatier/src/universal/routes
[1]  @ ./universal/routes/signup.js 25:23-92

```
and this 

```
node v5.4.0
npm v3.5.3

**Comment by mattkrick** [comment]
you need to start up rethinkdb

**Comment by fellz** [comment]
ok i just followed instructions on the page )
started server and still errors

```
 ERROR in ./universal/routes/login.js
[1] Module not found: Error: Cannot resolve module 'universal/modules/auth/containers/auth/AuthContainer' in /home/goracio/code/js/meatier/src/universal/routes
[1]  @ ./universal/routes/login.js 26:23-92
[1] 
[1] ERROR in ./universal/routes/signup.js
[1] Module not found: Error: Cannot resolve module 'universal/modules/auth/containers/auth/AuthContainer' in /home/goracio/code/js/meatier/src/universal/routes
[1]  @ ./universal/routes/signup.js 25:23-92
[1] 
```

**Comment by mattkrick** [comment]
I'm betting it's because your file system is case-sensitive (Ubuntu default). I *think* I fixed this in a commit I made last night, but I'm on a case-insensitive FS so I can't be sure. Try cloning the repo again & see if that fixes it

**Comment by fellz** [comment]
still that error

**Comment by fellz** [comment]
```
Hash: 9f574d604574cea81af7
[1] Version: webpack 2.0.2-beta
[1] Time: 44727ms
[1]    [2] multi app 40 bytes {4} [built]
[1]    [3] multi vendor 52 bytes {5} [built]
[1]     + 1115 hidden modules
[1] 
[1] ERROR in ./universal/routes/login.js
[1] Module not found: Error: Cannot resolve module 'universal/modules/auth/containers/auth/AuthContainer' in /home/goracio/code/js/meatier/src/universal/routes
[1]  @ ./universal/routes/login.js 26:23-92
[1] 
[1] ERROR in ./universal/routes/signup.js
[1] Module not found: Error: Cannot resolve module 'universal/modules/auth/containers/auth/AuthContainer' in /home/goracio/code/js/meatier/src/universal/routes
[1]  @ ./universal/routes/signup.js 25:23-92
[1] 
[1] ERROR in chunk app [initial]
[1] manifest_60b57d8c407a3030135f.js
[1] Cannot read property 'id' of null
[1] 
[1] npm
```

**Comment by fellz** [comment]
"universal/modules/auth/containers/auth/AuthContainer" and here is the path OS
"meatier/src/universal/modules/auth/containers/Auth"
so yes i guess problem with that but you didn't fix that in repo because i cloned and reinstalled and still error

**Comment by mattkrick** [comment]
Ohhh it was the subfolder. Cool, all fixed up now, thanks @feliz. Feel free to close if this fixed it

**Comment by fellz** [comment]
yep i changed this stuff myself ) and all compiled
